import type { Metadata } from "next";
import { AppShell, Header } from "@/components/app";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <AppShell header={<Header title="My CRUD App" />}>{children}</AppShell>
      </body>
    </html>
  );
}
