import type { Metadata } from "next";
import "./globals.css";
import { AppShell, Header } from "@/components/app";
import { SidebarTrigger } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <AppShell
          header={<Header title="My CRUD App" rightSlot={<SidebarTrigger />} />}
        >
          {children}
        </AppShell>
      </body>
    </html>
  );
}
